# Site settings
title: LinuxCNC
email: emc-developers@lists.sourceforge.net
description: "LinuxCNC: an open source CNC machine controller"
baseurl: "http://highlab.com/~seb/linuxcnc/wlo"
url: "http://linuxcnc.org"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
