# Site settings
title: LinuxCNC
email: emc-developers@lists.sourceforge.net
description: "LinuxCNC: an open source CNC machine controller"
baseurl: "/new"
url: "http://linuxcnc.org"
exclude: [ scripts, README.md ]
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
