# Site settings
title: LinuxCNC
email: emc-developers@lists.sourceforge.net
description: "LinuxCNC: an open source CNC machine controller"
legal: "\
    <p>LINUX® is the registered trademark of Linus Torvalds in the U.S. and \
    other countries.  The registered trademark Linux® is used pursuant \
    to a sublicense from LMI, the exclusive licensee of Linus Torvalds, \
    owner of the mark on a world-wide basis.</p> \
\
    <p>The LinuxCNC project is not affiliated with Debian.  Debian is a \
    registered trademark owned by Software in the Public Interest, Inc.</p> \
\
    <p>The LinuxCNC project is not affiliated with UBUNTU.  UBUNTU is a \
    registered trademark owned by Canonical Limited.</p>"
baseurl: ""
url: "http://linuxcnc.org"
exclude: [ scripts, README.md ]
include: [ .htaccess ]
#twitter_username: jekyllrb
github_username:  LinuxCNC

# Build settings
markdown: kramdown
permalink: pretty
collections:
  showcase:
    output: true
