#!/bin/bash

#
# Look in the jos_sections table for the defined section names, then import
# each one in turn.  Also import section "0", which has no name?
#
# In our Joomla config we have the following sections:
#     1: News
#     2: Documentation
#     3: Container
#

ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::Joomla.run({
        "dbname"   => "linuxcnc_org",
        "user"     => "emcboard",
        "password" => "F8&q114Z^",
        "host"     => "127.0.0.1",
        "section"  => "Documentation"
    })'
